model = "gpt-5.5"
model_reasoning_effort = "high"
personality = "pragmatic"

[tools]
web_search = true

[features]
memories = true

[projects."/Users/norikikomori/Developments/work/prd-dpai/e3-eui"]
trust_level = "trusted"

[projects."/Users/norikikomori/Developments/work/prd-dpai/e3-dpai-rag-eval"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-05-05T07:23:18Z"
source_type = "local"
source = "/Users/norikikomori/.codex/.tmp/bundled-marketplaces/openai-bundled"

[plugins."browser-use@openai-bundled"]
enabled = true
