model = "gpt-5.5"
model_reasoning_effort = "high"
personality = "pragmatic"

notify = ["/Users/komori/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[tools]
web_search = true

[features]
memories = true
goals = true
js_repl = false

[projects."/Users/norikikomori/Developments/work/prd-dpai/e3-eui"]
trust_level = "trusted"

[projects."/Users/norikikomori/Developments/work/prd-dpai/e3-dpai-rag-eval"]
trust_level = "trusted"

[projects."/Users/komori/dotfiles"]
trust_level = "trusted"

[projects."/Users/komori/life"]
trust_level = "trusted"

[projects."/Users/komori/Developments/research/sp-analysis"]
trust_level = "trusted"
[plugins."documents@openai-primary-runtime"]
enabled = true
[plugins."presentations@openai-primary-runtime"]
enabled = true
[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true
[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-06-29T04:49:25Z"
source_type = "local"
source = "/Users/komori/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-01T06:39:42Z"
source_type = "local"
source = "/Users/komori/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[desktop]
ambient-suggestions-enabled = true
appearanceTheme = "dark"
appearanceDarkCodeThemeId = "codex"
conversationDetailMode = "STEPS_COMMANDS"
followUpQueueMode = "queue"

[desktop.appearanceLightChromeTheme]
accent = "#339cff"
contrast = 45
ink = "#1a1c1f"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]
code = '"JetBrainsMono Nerd Font", ui-monospace, monospace'

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#ba2623"
skill = "#924ff7"

[desktop.appearanceDarkChromeTheme]
accent = "#0169cc"
contrast = 60
ink = "#fcfcfc"
opaqueWindows = false
surface = "#111111"

[desktop.appearanceDarkChromeTheme.fonts]
code = '"MesloLGS NF", ui-monospace, monospace'
ui = '"MesloLGS NF", ui-monospace, monospace'

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#e02e2a"
skill = "#b06dff"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/komori/life" = "zed"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/komori/.codex"
CODEX_HOME = "/Users/komori/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "a05cdd282c2717f076e11bc0e94b7b20e1fc4759dbe28440bd1c734953606a56"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.61825"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"
